// Re-exporta core sem dependências Node
export {
  VelixClient,
  VelixError,
  VelixApiError,
  VelixNetworkError,
  OnboardingModule,
  CheckinModule,
  LgpdModule,
  MeModule,
  EventsModule,
  TimeModule,
} from '@velixbiometrics/sdk-core'
export type {
  VelixConfig,
  Envelope,
  ApiResponse,
  DocumentType,
  IdentityRole,
  OnboardingRequest,
  OnboardingFrameResult,
  OnboardingResponse,
  LivenessAction,
  LivenessSample,
  LivenessBlock,
  CheckinLocation,
  CheckinIdentifyRequest,
  CheckinIdentifyResponse,
  CheckinResult,
  DeletionRequest,
  DeletionRequestResponse,
  MeResponse,
  Person,
  CreateGuestRequest,
  GuestResponse,
  PaginatedResult,
} from '@velixbiometrics/sdk-core'
